name: fluttership
description: A Project Where I Share The Things I Love To Share

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0" #I don't use nullsafety to use nullsaftety replace 2.7.0 with 2.12.0

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^1.2.0

flutter_native_splash:
  color: "#0063dd"
  image: assets/logo.png #u must place logo.png in your assets folder
  android: true
  ios: true



flutter:
  uses-material-design: true
  assets:
  - assets/
